### ISSUE TITLE
Passenger table doesn't flow well from one page to another

### ISSUE THREAD

**Issue by Anbranin** [umts/st-pax#177] opened 2019-11-07 20:51 UTC
Rows get split in the middle if they flow onto the next page.

**Comment by werebus** [comment] 2019-11-14 15:55
Have you confirmed this behavior? I can't.

[All passengers 2019-11-14.pdf](https://github.com/umts/st-pax/files/3847390/All.passengers.2019-11-14.pdf)

**Comment by Anbranin** [comment] 2019-11-14 16:01
It doesn't happen on the PDF, it only happens under one specific scenario, and that is printing it out on non-tabloid-size paper. If you attempt a print with 8.5x11 you'll get this behavior. So I think closing #176 will close this issue.

**Comment by werebus** [comment] 2019-11-14 16:42
OK so.... duplicate of #176?

**Closed by werebus** 2019-11-14 16:42 UTC

**Comment by Anbranin** [comment] 2019-11-14 16:52
Yeah I guess except this was describing a specific unpleasant symptom that's all
