### ISSUE TITLE
Weird error pops up on logout

### ISSUE THREAD

**Issue by AkivaGreen** [umts/st-pax#58] opened 2017-08-31 15:35 UTC
It still logs you out, but...

![screen shot 2017-08-31 at 11 33 26 am](https://user-images.githubusercontent.com/15308734/29931803-4c6de882-8e40-11e7-807b-8ca3ff735243.png)

**Comment by dfaulken** [comment] 2017-08-31 15:53
Probably a too generic invocation of the datatables logic in the Javascript. We should only be trying to create a datatable if we're on the passengers index page, not turbolinking to the logout page.

**Comment by werebus** [comment] 2017-09-11 17:05
So, according to the page referenced in the error message.  This is caused by reinitializing `DataTables` with **different** options to the existing DataTable.

I think this is related to the admin/non-admin invocation.  [Here][1], and then again [here][2].  Is there a chance that loging out causes that div to have *both* the `.admin_table` *and* the `.dispatch_table` class?

**Comment by Chauce** [comment] 2017-09-12 17:24
Branch `logout-error` contains the fix for this now :)

**Comment by Chauce** [comment] 2018-06-19 17:34
Fix for this will likely also close #96

**Comment by Chauce** [comment] 2018-06-20 17:16
<img width="585" alt="screen shot 2018-06-20 at 1 12 22 pm" src="https://user-images.githubusercontent.com/19393198/41673683-a2494ef4-748b-11e8-84b0-52b32d08b272.png">
It's _possible_ that the fix for #96 will **not** close this issue. I think the cause of this issue is that we have a dispatcher table and an admin table, and once you log out, the site is briefly trying to initialize both.

**Closed** 2019-09-30 13:27 UTC
Labels: MVP
