### ISSUE TITLE
Email already in use issue

### ISSUE THREAD

**Issue by umasstransit** [umts/st-pax#206] opened 2020-01-21 20:17 UTC
I attempted to re-register a Permanent passenger but couldnt seem to do so as it kept saying the spire ID or email was already in use. 

[90](https://st-pax.admin.umass.edu/users/90)

**Comment by werebus** [comment] 2020-02-19 16:24
@Anbranin, If I recall correctly, we couldn't reproduce this, right?

**Comment by Anbranin** [comment] 2020-02-20 12:42
Correct. We could not reproduce it without doing something incorrect on the part of the user--that is, pressing enter to submit the form.
It should no longer be a problem due to dispatchers being able to see the archived passengers and indeed I have heard nothing. Closing this issue until we hear something else, which will probably be in the form of a new issue.

**Closed by Anbranin** 2020-02-20 12:42 UTC
Labels: bug, unconfirmed
