### ISSUE TITLE
Ability to Mass Extract Contact Info

### ISSUE THREAD

**Issue by umasstransit** [umts/st-pax#199] opened 2019-12-09 17:58 UTC
Turns out, the ability to extract all the pax emails from past and present is a feature I didn't think I needed until I needed to send a huge email to all of them. If there is a way to export to excel, or a copy emails to clipboard button, that would help my stats life out a lot. 

[80](https://st-pax.admin.umass.edu/users/80)

**Comment by Anbranin** [comment] 2019-12-09 18:02
duplicate of #144

**Closed by Anbranin** 2019-12-09 18:02 UTC
Labels: addition, duplicate, unconfirmed
